# Generated by Django 6.0.1 on 2026-02-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscription'),
        ),
        migrations.AddField(
            model_name='chefassignment',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.subscription'),
        ),
    ]
