# Generated by Django 6.0.1 on 2026-02-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=4.5)),
                ('is_available', models.BooleanField(default=True)),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
    ]
